cache: bundler
language: ruby
sudo: false
notifications:
  email: false

rvm:
  - 2.3.4
  - 2.4.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake ci

jdk: oraclejdk8
