# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8507e365a356e95dc16f6e75542d265ac310ef22a5abbad237b853c2b186c8ca792b476f5215a1de35655e18aad96f955052b3fbe5d22eea8c63762f53fd83e4

test:
  secret_key_base: 2beebeaaa326ca2c01b2ac3f7c30609a86b73d2ba0e0304417e3a8a98c4f77d5ed07057659fbd8b7929afc6532883014a05f136b5a9bfcbe6d07ebf32e5487e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
