EMAIL_TO: 'fake-email@example.com'
GEOMONITOR_TOLERANCE: 0.8
GOOGLE_ANALYTICS_ID: 'UA-XXXXX-X'
GOOGLE_SITE_VERIFICATION: 'I1DQ46tUnPOrYpnhDUsy5tOL22oywWb2LyUTwT8M-HU'
HOSTNAME: 'HOST'
INSTITUTION: 'Stanford'

PROXY_URL: 'http://www.example.com/restricted'

RESTRICTED_URL: 'http://www.example-services.com'

SQUASH_API_HOST: 'http://squash-host.example.com'
SQUASH_API_KEY: 'squash-api-key'
SQUASH_DISABLE: <%= (Rails.env.development? || Rails.env.test?) %>

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'
  